spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/flavor_booking_test?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  exp-access-token: 86400 #86400 # 1 day
  exp-refresh-token: 604800 # seconds
  secretKey: 9e8896ae0f4b75d6633c835079b60a73ed0102977da741d3ebe357745fcc6a1c



